server:
  port: 8080
  servlet:
    context-path: /api/v1
spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/cinema"
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  security:
    enabled: false
  servlet:
    multipart:
      enabled: true
      max-file-size: 50MB
      max-request-size: 50MB
app:
  cors:
    allowed-origins: http://localhost:5173
file:
  upload:
    dir: uploads/movies
    max-size: 52428800
    allowed-types:
      - image/jpeg
      - image/png
      - image/webp
      - video/mp4
      - video/mpeg
      - video/quicktime
      - video/x-msvideo
      - video/webm

jwt:
  signerKey: "92f5c84902ace8e29f5c7b38a6b631ee957ff3de1e5b550f2ca837b1923d67ea"
sePay:
  bank:
    account: "0764386915"
    name: "MBBank"
  template: "compact"
  api:
    key: "NKKH29HARK93YOERR7FQZFBXYWEWMWXW35LIS5SB1CNJ1V4ESRBIPIZS8JQO7NN2"
